language: cpp
dist: bionic
sudo: false
os: linux

env:
  global:
    - PROJECT_VERSION_MAJOR="0"
    - PROJECT_VERSION_MINOR="8"
    - PROJECT_VERSION_PATCH="${TRAVIS_BUILD_NUMBER}"
    - PROJECT_VERSION="${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}"
branches:
  only:
    - master
    - /^v.*$/

matrix:
  include:
    - env: COMPILER=g++-8 BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
#            - sourceline: 'ppa:mhier/libboost-latest'
#            - ubuntu-toolchain-r-test
          packages:
            - g++-8
#            - boost1.67
    - env: COMPILER=g++-8 BUILD=Release STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
#            - sourceline: 'ppa:mhier/libboost-latest'
#           - ubuntu-toolchain-r-test
          packages:
            - g++-8
#            - boost1.67

before_script:
#
#  - sudo wget -O boost_1_65_1.tar.gz https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.gz/download
#  - sudo tar xzvf boost_1_65_1.tar.gz > build.log 2>&1
#  - cd boost_1_65_1/
#  - sudo ./bootstrap.sh --with-libraries=program_options --prefix=/usr/local
#  - sudo ./b2 link=shared threading=multi variant=release
#  - sudo ./b2 install > build.log 2>&1
  - env
  - export SRC_DIR="`pwd`"
  - wget https://cmake.org/files/v3.13/cmake-3.13.4-Linux-x86_64.sh
  - sudo sh cmake-3.13.4-Linux-x86_64.sh -- --skip-license --prefix=/usr
  - export DOWNLOAD_ROOT="$HOME/download"; if [ ! -d "$DOWNLOAD_ROOT" ]; then mkdir -p "$DOWNLOAD_ROOT"; fi
  - export BOOST_DOWNLOAD_URL="https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz/download"
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - if [ ! -f "$DOWNLOAD_ROOT/boost.tar.gz" ]; then wget --no-verbose --output-document="$DOWNLOAD_ROOT/boost.tar.gz" "$BOOST_DOWNLOAD_URL"; fi
  - if [ ! -d "$BOOST_ROOT" ]; then mkdir -p "$BOOST_ROOT" && tar xzf "$DOWNLOAD_ROOT/boost.tar.gz" --strip-components=1 -C "$BOOST_ROOT"; fi
  - if [ ! -f "$BOOST_ROOT/b2" ]; then cd "$BOOST_ROOT"; ./bootstrap.sh --with-libraries=program_options,system,thread,regex; fi
  - cd "$BOOST_ROOT"; ./b2 threading=multi --prefix="$BOOST_ROOT" -d0 install
  - cd "$SRC_DIR";
script:
  - cmake .
  - cmake --build .
#  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T hcch-$PROJECT_VERSION-Linux.deb -uangelskieglazki:$BINTRAY_API_KEY "https://api.bintray.com/content/angelskieglazki/aeco/hcch/$TRAVIS_BUILD_NUMBER/hcch-$PROJECT_VERSION-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    tags: true
